config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "/home/about" => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/search' => 'search#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  has_many :book_comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  validates :name, uniqueness: true
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!,except: [:top, :about]
   before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
def create
    @book = Book.find(params[:book_id])
    @user = @book.user
    comment = current_user.book_comments.build(book_comment_params)
    comment.book_id = @book.id
    comment.save
end

def destroy
    @book = Book.find(params[:book_id])
    @user = @book.user
    book_comment = @book.book_comments.find(params[:id])
		book_comment.destroy
end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end



  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @books = Book.find(params[:id])
    flash[:notice] = "Book was successfully destroyed."
    @books.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: params[:book_id])
    favorite.save
    # redirect_back(fallback_location: root_path)
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    favorite.destroy
    # redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @value = params[:value]
    @model = params[:model]
    @how = params[:how]
    @datas = search_for(@how, @model, @value)
  end

   private

  def perfect_match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'perfect_match'
      perfect_match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
   @user = current_user
   @book = Book.new
   @users = User.all
 end



 def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
 end

 def edit
   # @users = User.new
   @user = User.find(params[:id])
   if @user != current_user
     redirect_to user_path(current_user.id)
   end
 end

 def update
    @user = User.find(params[:id])
    if@user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
     render :edit
    end
 end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_book-comment.html.erb
<%= form_with(model:[book, book_comment], remote: true) do |f| %>
  <%= f.text_area :comment, class: "inputComment", size:"90x5" %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/_book-delete.html.erb
<% book.book_comments.each do |book_comment| %>
  <div class="comments">
      <tr>
       <td>
         <%= attachment_image_tag book_comment.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %> <br>
         <%= user.name %>
        </td>
        <td>
          <%= book_comment.comment %>
        </td>
        <% if book_comment.user == current_user %>
         <div class="comment-delete">
           <td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class:"btn btn-danger", method: :delete, remote: true %></td>
         </div>
        <% end %>
        </tr>
   </div>
<% end %>

app/views/book_comments/create.js.erb
$("#comments-count").html("コメント数: <%= @book.book_comments.count %>");
$("#book_delete").html("<%= j(render partial: 'book_comments/book-delete', locals:{ book: @book, user: @user }) %>");
$(".inputComment").val('');

app/views/book_comments/destroy.js.erb
$("#comments-count").html("コメント数: <%= @book.book_comments.count %>");
$("#book_delete").html("<%= j(render partial: 'book_comments/book-delete', locals:{ book: @book, user: @user }) %>");
$(".inputComment").val('');

app/views/books/_list.html.erb
<div class="profile-container">
   <h2>User info</h2>
    <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
   <table class="table">
        <tr></tr>
        <tr>
          <th>name</th>
          <th><div class="profile-name"><%= user.name %></div></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><div class="profile-introduction"><%= user.introduction %></div></th>
        </tr>
        <tr>
          <th>follows</th>
          <th><%=link_to user.followings.count, user_followings_path(user) %></th>
        </tr>
        <tr>
          <th>followers</th>
          <th><%= link_to user.followers.count, user_followers_path(user) %></th>
        </tr>
   </table>
      <% if user.id == current_user.id %>
        <%= link_to edit_user_path(user) ,class:"btn btn-outline-secondary btn-block", method: :get do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      <% end %>

      <% if user.id != current_user.id %>
         <% if current_user.following?(user) %>
           <%= link_to "フォロー外す", user_relationships_path(user.id),class:"btn btn-info", method: :delete %>
          <% else %>
           <%= link_to "フォローする", user_relationships_path(user.id),class:"btn btn-success", method: :post %>
          <% end %>
      <% end %>
</div>

app/views/books/edit.html.erb
<main>
 <p id="notice"></p>
 <div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%if @book.errors.any? %>
         <div class="error_explanation">
            <h3><%= @book.errors.count %>&nbsp;error prohibited this obj from being saved: </h3>
              <ul class="error-list">
               <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
               <% end %>
              </ul>
          </div>
        <% end %>
      <%= form_with model:@book, local:true do |f| %>
       <div class="form-group">
        <label for="inputName">Title</label>
        <%= f.text_field :title, autofocus: true, id:"inputName", class:"form-control name"%>
       </div>

        <div class="form-group">
          <label for="inputIntroduction">Opinion</label>
          <%= f.text_area :body, autofocus: true, id:"inputIntroduction", class:"form-control introduction"%>
        </div>
        <div class="form-group">
        <%= f.submit "Update Book", class:"btn btn-success"%>
        </div>
      <% end %>
      <div><%= link_to "Show", book_path(@book) %>
           |
           <%= link_to "Back", "/books" %>
      </div>
   </div>
  </div>
 </div>
</main>

app/views/books/index.html.erb
<main>
     <p id="notice"></p>
     <div class="container px-5 px-sm-0">
       <%if @book.errors.any? %>
         <div class="error_explanation">
            <h3><%= @book.errors.count %>&nbsp;error prohibited this obj from being saved: </h3>
              <ul class="error-list">
               <% @book.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
               <% end %>
              </ul>
          </div>
        <% end %>
       <div class="row">
         <div class="col-md-3">
           <%= render 'books/list', user: @user %>
            <h2>New book</h2>
            <%= form_with model: @book, local:true do |f| %>
             <label>Title</label><br>
             <%= f.text_field :title %><br>
             <label>Opinion</label><br>
             <%= f.text_area :body %><br>
             <%= f.submit 'Create Book', class:"btn btn-success" %>
             <% end %>
         </div>
            <div class="col-md-8 offset-md-1">
              <h2>Books</h2>
              <table class="table table-hover table-inverse">
                <thead>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>
                <tbody>
                  <% @books.each do |book| %>
                  <tr>
                    <td>
                      <%= link_to user_path(book.user) do %>
                       <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
                      <% end %>
                    </td>
                    <td><%= link_to book.title, book %></td>
                    <td><%= book.body %></td>

                    <td id="book_<%= book.id %>">
                     <%= render 'favorites/favorite-btn', book: book %>
                    </td>
                    <td>コメント数：<%= book.book_comments.count %></td>
                  </tr>
                  <% end %>
                </tbody>
              </table>
            </div>
     　 </div>
    </div>
</main>

app/views/books/show.html.erb
<main>
    <p id="notice"></p>
    <div class="container px-5 px-sm-0">
       <div class="row">
            <div class="col-md-3">
                <%= render 'books/list', user: @user %>
               <h2>New book</h2>
                <%= form_with model: @book_new, local:true do |f| %>
                  <label>Title</label><br>
                  <%= f.text_field :title %><br>
                  <label>Opinion</label><br>
                  <%= f.text_area :body %><br>
                  <%= f.submit 'Create Book', class:"btn btn-success" %>
                <% end %>
            </div>
          <div class="col-md-8 offset-md-1">
               <h2>Book detail</h2>
                <table class="table">
                 <tbody>
                   <tr>
                    <td>
                        <%= link_to user_path(@user.id) do %>
                          <%= attachment_image_tag @user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %> <br>
                          <%= @user.name %>
                        <% end %>
                    </td>
                    <td><%= link_to @book.title %></td>
                    <td><%= @book.body %></td>

                    <td id="book_<%= @book.id %>">
                        <%= render 'favorites/favorite-btn', book:@book %>
                    
                         <td id="comments-count">コメント数：<%= @book.book_comments.count %></td>
                      <td>
                        <% if @book.user == current_user %>
                         <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-sm btn-success" %>
                        <% end %>
                      </td>
                      <td>
                        <% if @book.user == current_user %>
                         <%= link_to "Destroy", book_path(@book), class:"btn btn-sm btn-danger", method: :delete %>
                        <% end %>
                      </td>  
                    </td>
                   </tr>
                 </tbody>
                </table>
                <table id="book_delete">
                    <%= render partial: 'book_comments/book-delete', locals:{ book: @book, user: @user } %>
                </table>
                  <div id="book_comment">
                   <%= render partial: 'book_comments/book-comment', locals:{ book: @book, book_comment: @book_comment } %>
                 </div>
            </div>
        </div>
    </div>
</main>

app/views/favorites/_favorite-btn.html.erb
 <% if book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        <span class="fa fa-heart like-btn-unlike"><%= book.favorites.count %></span>
      <% end %>
    </p>
<% else %>
    <p class="favo-color">
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
         <span class="fa fa-heart like-btn"><%= book.favorites.count %></span>
      <% end %>
    </p>
<% end %>
</td>
  

app/views/favorites/create.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %>").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/users/edit.html.erb
<main>
   <p id="notice"></p>
   <div class="container">
     <div class="row">
       <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
   
        <%if @user.errors.any? %>
            <div class="error_explanation">
               <h3><%= @user.errors.count %>&nbsp;error prohibited this obj from being saved: </h3>
                 <ul class="error-list">
                  <% @user.errors.full_messages.each do |msg| %>
                   <li><%= msg %></li>
                  <% end %>
                 </ul>
             </div>
           <% end %>
        <%= form_with model:@user, local:true do |f| %>
         <div class="form-group">
          <label for="inputName">Name</label>
          <%= f.text_field :name, autofocus: true, id:"inputName", class:"form-control name"%>
         </div>
         <div class="form-group">
          <%= attachment_image_tag @user, :profile_image, :fill, 60, 60 %>
          <label for="inputImage">Image</label>
          <%= f.attachment_field :profile_image, placeholder: "プロフィール画像", class:"form-control-file user_image"%>
         </div>
         <div class="form-group">
          <label for="inputIntroduction">Introduction</label>
          <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", class:"form-control introduction"%>
         </div>
         <div class="form-group">
          <%= f.submit "Update User", class:"btn btn-secondary"%>
         </div>
        <% end %>
       </div>
     </div>
   </div>
</main>

app/views/users/index.html.erb
<main>
       <p id="notice"></p>
       <div class="container px-5 px-sm-0">
          <div class="row">
                   <div class="col-md-3">
                     <%= render 'books/list', user: @user %>
                       <h2>New book</h2>
                        <%= form_with model: @book, local:true do |f| %>
                          <label>Title</label><br>
                          <%= f.text_field :title %><br>
                          <label>Opinion</label><br>
                          <%= f.text_area :body %><br>
                          <%= f.submit 'Create Book', class:"btn btn-success" %>
                        <% end %>
                   </div>
                   <div class="col-md-8 offset-md-1">
                       <h2>Users</h2>
                       <table class="table">
                           <thead>
                               <tr>
                                   <th>image</th>
                                   <th>name</th>
                                   <th colspan="3"></th>
                               </tr>
                           </thead>
                           <tbody>
                            <% @users.each do |user| %>
                               <tr>
                                   <td><%= attachment_image_tag user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %></td>
                                   <td><%= user.name %></td>
                                   <td>フォロー数: <%= user.followings.count %></td>
                                   <td>フォロワー数: <%= user.followers.count %></td>
                                   <td>
                                     <% if user_signed_in? && user != @user %>
                                     <% if current_user.following?(user) %>
                                        <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
                                      <% else %>
                                        <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
                                      <% end %>
                                      <% end %>
                                    </td>
                                   <td><%= link_to "Show", user_path(user.id) %></td>
                               </tr>
                            <% end %>
                           </tbody>
                       </table>
               </div>
           </div>
       </div>
</main>

app/views/users/show.html.erb
<main>
     <p id="notice"></p>
     <div class="container px-5 px-sm-0">
       <div class="row">
         <div class="col-md-3">
          <%= render 'books/list', user: @user %>
         <h2>New book</h2>
          <%= form_with model: @book, local:true do |f| %>
            <label>Title</label><br>
            <%= f.text_field :title %><br>
            <label>Opinion</label><br>
            <%= f.text_area :body %><br>
            <%= f.submit 'Create Book', class:"btn btn-success" %>
          <% end %>
        </div>
        <div class="col-md-8 offset-md-1">
          <h2>Books</h2>
          <table class="table">
              <thead>
                  <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                  </tr>
              </thead>
               <% @books.each do |book| %>
                   <tbody>
                     <tr>
                      <td><%= link_to user_path do %>
                          <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, fallback: "no_image.jpg", size:'40x40' %>
                          <% end %>
                      </td>
                      <td><%= link_to book.title ,book %></td>
                      <td><%= book.body %></td>
                     </tr>
                   </tbody>
               <% end %>
            </table>
         </div>
       </div>
     </div>
</main>