config/routes.rb
Rails.application.routes.draw do
  get 'search/search'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get "/home/about" => 'homes#about'
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :update, :index] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
  get '/search' => 'search#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  has_many :book_comments, dependent: :destroy
  
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
 
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, length: { in: 2..20 }
  validates :introduction, length: {maximum: 50}
  validates :name, uniqueness: true
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @book = Book.new
    @books = Book.all
    @user = current_user
  end

  def create
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book.id)
    else
     @books = Book.all
     render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end



  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
       redirect_to book_path(@book.id)
    else
      @books = Book.all
      render :edit
    end
  end

  def destroy
    @books = Book.find(params[:id])
    flash[:notice] = "Book was successfully destroyed."
    @books.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top

  end

  def about
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search
    @value = params[:value]
    @model = params[:model]
    @how = params[:how]
    @datas = search_for(@how, @model, @value)
  end

   private

  def perfect_match(model, value)
    if model == 'user'
      User.where(name: value)
    elsif model == 'book'
      Book.where(title: value)
    end
  end

  def forward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "#{value}%")
    end
  end

  def backward(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}")
    end
  end

  def partical(model, value)
    if model == 'user'
      User.where("name LIKE ?", "%#{value}%")
    elsif model == 'book'
      Book.where("title LIKE ?", "%#{value}%")
    end
  end

  def search_for(how, model, value)
    case how
    when 'perfect_match'
      perfect_match(model, value)
    when 'forward'
      forward(model, value)
    when 'backward'
      backward(model, value)
    when 'partical'
      partical(model, value)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def index
   @user = current_user
   @book = Book.new
   @users = User.all
 end



 def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
 end

 def edit
   # @users = User.new
   @user = User.find(params[:id])
   if @user != current_user
     redirect_to user_path(current_user.id)
   end
 end

 def update
    @user = User.find(params[:id])
    if@user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
     render :edit
    end
 end

private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>Bookers2</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      <script src="https://kit.fontawesome.com/*******.js" crossorigin="anonymous"></script>
      <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
       <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class= "container">
          <%= link_to "Bookers", root_path, class: "navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item active">
                  <%= link_to user_path(current_user), class: "nav-link" do %>
                    <i class="fas fa-home"></i>
                      Home
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to users_path, class: "nav-link" do %>
                    <i class="fas fa-users"></i>
                     Users
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to books_path, class: "nav-link" do  %>
                    <i class="fas fa-book-open"></i>
                     Books
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
                    <i class="fas fa-sign-out-alt"></i>
                     logout
                  <% end %>
                </li>
              <% else %>
                <li class="nav-item active">
                  <%= link_to root_path, class: "nav-link" do %>
                    <i class="fas fa-home"></i>
                     Home
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to home_about_path, class: "nav-link" do %>
                    <i class="fas fa-link"></i>
                     About
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to new_user_registration_path, class: "nav-link" do %>
                    <i class="fas fa-user-plus"></i>
                     sign up
                  <% end %>
                </li>
                <li class="nav-item active">
                  <%= link_to new_user_session_path, class: "nav-link" do %>
                    <i class="fas fa-sign-in-alt"></i>
                     login
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </body>
      <div class="container">
          <div class="col-xs-6 col-xs-offset-3 text-center" style="margin-top: 25px;">
            <% if user_signed_in? %>
              <%= form_with url:search_path, method: :get, local: true do |f| %>
                <%= f.text_field :value %>
                <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
                <%= f.select :how, options_for_select({ "完全一致" => "perfect_match", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partical"  }) %>
                <%= f.submit :"検索" %>
              <% end %>
            <% end %>
          </div>
      </div>
      
      <div class="flash-success"><%= flash[:notice] %></div>
      
      <%= yield %>
      <footer>
         <div class="container mt-5">
           <div class="row">
             <div class="mx-auto">
              <p>CopyRight Infratop.inc</p>
             </div>
           </div>
         </div>
       </footer>
</html>